### ISSUE TITLE
How to read vtk file

### ISSUE THREAD

**Issue by yejinhong10** [prabhuramachandran/mayavi-tutorial#5]
Thanks so much for your tutorial on mayavi.
I would like to visualize vtk files using mayavi, is there any way to do so? I tried using https://mayavi.sourceforge.net/docs/guide/ch04.html, but it says mayavi does not have modules such as mayavi or open.

**Comment by prabhuramachandran** [comment]
Use `mlab.pipeline.open('supported_file_name.ext')`
